name: "Cache Node Modules"
runs:
  using: "composite"
  steps:
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
          ./modules/*/node_modules
          ./app/node_modules
        key: ${{ runner.os }}-modules-${{ env.CACHE_ID }}-${{ hashFiles('**/yarn.lock') }}
