name: Deploy FrontEnd
inputs:
  PINATA_KEY:
    description: "Pinata key from GitHub secrets"
    required: true
  PINATA_SECRET:
    description: "Pinata secret from GitHub secrets"
    required: true
  FLEEK_API_KEY:
    description: "Fleek API key"
    required: true
runs:
  using: "composite"
  steps:
    - id: ipfs-deploy-docs
      name: ipfs-deploy-docs
      uses: aquiladev/ipfs-action@v0.2.1
      with:
        path: ./app/build
        service: pinata
        pinataKey: ${{ inputs.PINATA_KEY }}
        pinataSecret: ${{ inputs.PINATA_SECRET }}

    - name: Build fleek app mainnet
      id: build-fleek-app-mainnet
      if: ${{ github.ref == 'refs/heads/mainnet' }}
      run: yarn set-fleek app
      shell: bash

    - name: Build fleek app devnet
      id: build-fleek-app-devnet
      if: ${{ github.ref == 'refs/heads/devnet' }}
      run: yarn set-fleek devnet
      shell: bash

    - id: deploy-app
      if: ${{ github.ref == 'refs/heads/mainnet' || github.ref  == 'refs/heads/devnet' }}
      uses: fleekhq/action-deploy@v1
      with:
        apiKey: ${{ inputs.FLEEK_API_KEY }}

    - name: View this Build!
      run: echo "LATEST BUILD https://hydraswap-io-app.mypinata.cloud/ipfs/${{steps.ipfs-deploy.outputs.cid}}"
      shell: bash
