name: "Notify slack success"
inputs:
  JOB_NAME:
    description: "Job name to show on slack"
    default: ${{ github.job }}
  SLACK_NOTIFICATIONS_BOT_TOKEN:
    descripton: "The token to notify slack"
    required: true
runs:
  using: "composite"
  steps:
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: gitops
        status: ${{ inputs.JOB_NAME }}-SUCCESS
        color: good

    - name: Notify slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: gitops
        status: ${{ inputs.JOB_NAME }}-FAILURE
        color: danger
