env:
  CACHE_ID: tc-271022-1

on:
  push:
    branches:
      - devnet

name: Publish Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hydraswap-io/hydraswap-ci:0.0.24
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_READ_TOKEN }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

      - name: Get current date for turbocache
        if: ${{ steps.release.outputs.release_created }}
        id: date
        run: echo "::set-output name=date::$(date +'%U')"

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add safe directory for github
        # The following is required as we use git in one of our scripts (app/scripts/save-ghc.sh) and it wont work due to
        # /__w/hydraprotocol/hydraprotocol being owned by a different user because of this: https://github.blog/2022-04-12-git-security-vulnerability-announced/
        run: git config --global --add safe.directory /__w/hydraprotocol/hydraprotocol

      - name: "Load Turbo Cache"
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/cache@v2
        with:
          key: turbocache-${{ env.CACHE_ID }}${{ steps.date.outputs.date }}-${{ github.run_id }}
          restore-keys: turbocache-${{ env.CACHE_ID }}${{ steps.date.outputs.date }}
          path: .turbocache

      - name: "Investigate dirs"
        run: mkdir -p .turbocache && ls -la && ls -la .turbocache

      - name: Cache Node Modules
        if: ${{ steps.release.outputs.release_created }}
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./modules/*/node_modules
            ./app/node_modules
          key: ${{ runner.os }}-modules-${{ env.CACHE_ID }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node Dependencies
        id: install-yarn-deps
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: yarn build --filter=@hydraprotocol/math && yarn build

      - name: Setup publish access
        if: ${{ steps.release.outputs.release_created }}
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - run: yarn set-version ${VERSION}
        if: ${{ steps.release.outputs.release_created }}
        env:
          VERSION: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/cli/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/config/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/core/modules/hydra-math/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/idls/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/sdk/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/utils-node/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/utils-solana/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/val/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - uses: bluecargo/npm-publish@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: https://registry.npmjs.org
          access: public
          tag: next
          check-version: false
          package: ./modules/wasm-loader/package.json
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}
