env:
  CACHE_ID: tc-271022-1

on:
  push:
    branches:
      - mainnet

name: Publish npm

jobs:
  release-please:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hydraswap-io/hydraswap-ci:0.0.24
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_READ_TOKEN }}
    steps:
      - name: Setup publish access
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Node Modules
        if: ${{ steps.release.outputs.release_created }}
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./modules/*/node_modules
            ./app/node_modules
          key: ${{ runner.os }}-modules-${{ env.CACHE_ID }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node Dependencies
        id: install-yarn-deps
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --frozen-lockfile --ignore-scripts

      - run: yarn set-version $(yarn -s get-version)

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: yarn build --filter=@hydraprotocol/math && yarn build

      - run: yarn set-npm-tag $(yarn -s get-version) latest
